UBER_CLIENT_ID: "INSERT_CLIENT_ID_HERE"
UBER_CLIENT_SECRET: "INSERT_CLIENT_SECRET_HERE"
development:
  MAILER_HOST: "<INSERT LOCAL SERVER>(Example localhost: 3000)"
  UBER_SERVER_TOKEN: "INSERT_UBER_SERVER_TOKEN_HERE"
test:
  MAILER_HOST: "<INSERT TEST SERVER>(Example localhost: 3000)"
  UBER_SERVER_TOKEN: "INSERT_UBER_SERVER_TOKEN_HERE"
production:
  MAILER_HOST: "<INSERT PROD DOMAIN>(Example my-heroku-app.herokuapp.com"
  UBER_SERVER_TOKEN: "INSERT_UBER_SERVER_TOKEN_HERE"